### ISSUE TITLE
Add a skate feature to linkify feature flags

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/slack-gradle-plugin#408]
It would be cool if we could do a config to recognize certain patterns in code like our internal enum-based flags and linkify them to where they're defined on a backend server. Could work similar to how github can linkify common bugtracker IDs

**Comment by arpita184** [comment]
Further conversation at: https://slack-pde.slack.com/archives/C058XKY4DRV/p1688684299374309

**Comment by ZacSweers** [comment]
This is done
