### ISSUE TITLE
Add Upcoming Release Train Relevant Dates (string freeze, release cut, release etc)

### ISSUE THREAD

**Issue by kateliu20** [slackhq/slack-gradle-plugin#502]
Display contextual announcements in IDE based on file, such as upcoming release trains

Add a UI component to show the next upcoming release date in IDE. On the day of launch, Skate can display a banner with the specific announcement.

Would need a structured format of some sort to read from on IDE start.

**Comment by ZacSweers** [comment]
Closing this in favor of just sticking with standard shared calendars :). Might be a good place for FYI banners, but we'll wait until we have more use cases
