### ISSUE TITLE
Roboletric setup seems broken for non-Slack usage

### ISSUE THREAD

**Issue by chrisbanes** [slackhq/slack-gradle-plugin#917]
Using the `robolectric()` feature via the DSL turns on various things, including `isIncludeAndroidResources`. But it also seems to force a dependency on a `robolectricCoreProject` module. What is this module?

If I don't provide this module, then the build breaks.

**Comment by ZacSweers** [comment]
sorry was on sabbatical and missed this. We can make this optional 👍. That's sort of like a "common robolectric APIs" module, we put some robolectric plugins there in our project
